require("mycfg.greeting")
require("mycfg.useclipboard")
require("mycfg.tabsize")
require("mycfg.remapnetrw")
require("mycfg.bracketcompletion").setup()
require("mycfg.gofmt_on_save").setup()
require("mycfg.diagnostics")
require("mycfg.goimports_on_save")
